version: "3.8"

services:
  app:
    build: .
    container_name: htn-translation-layer
    ports:
      - "8000:8000"
    environment:
      PROTOCOL: HTTP
      PORT: 8000
      ORIGINS: localhost:8000
      ATLAS_URI: mongodb://mongodb:27017/htn-translation-layer
      HTTPS_CERT: /etc/letsencrypt/live/hoosat.fi/cert.pem
      HTTPS_KEY: /etc/letsencrypt/live/hoosat.fi/privkey.pem
      HTTPS_CA: /etc/letsencrypt/live/hoosat.fi/chain.pem
      EMAIL_SERVER_TYPE: service
      EMAIL_SERVICE:
      EMAIL_USERNAME:
      EMAIL_PASSWORD:
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: my_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: htn-translation-layer
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
